### ISSUE TITLE
Installation Packages error

### ISSUE THREAD

**Issue by AxelTdev** [oanda/oandapy#53]
Hi,
When i try to install python packages with:
`sudo pip install oandapy`

There is this error : 
`Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-xmyyfrsm/pysimplemodel/
`
My Python version is 2.7.13.
This is the complete output:
` Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-xmyyfrsm/pysimplemodel/setup.py", line 6, in <module>
        from simple_model.__version__ import __version__
      File "/tmp/pip-install-xmyyfrsm/pysimplemodel/simple_model/__init__.py", line 2, in <module>
        from .builder import model_builder, model_many_builder
      File "/tmp/pip-install-xmyyfrsm/pysimplemodel/simple_model/builder.py", line 3, in <module>
        from .models import Model
      File "/tmp/pip-install-xmyyfrsm/pysimplemodel/simple_model/models.py", line 5, in <module>
        from .fields import ModelField, Unset
      File "/tmp/pip-install-xmyyfrsm/pysimplemodel/simple_model/fields.py", line 24
        return (f'ModelField(model_class={self.model_class!r}, name={self.name!r}, '
                                                                                   ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-xmyyfrsm/pysimplemodel/
`
Thanks in advance

**Comment by chemlavictor** [comment]
I Have the same problem

**Comment by Draichi** [comment]
same here

but i could install using `pip install git+https://github.com/oanda/oandapy.git`
