### ISSUE TITLE
module 'oandapy' has no attribute 'OandaError'

### ISSUE THREAD

**Issue by david2588e** [oanda/oandapy#55]
Traceback (most recent call last):

  File "<ipython-input-5-27190e878d22>", line 5, in <module>
    import backtrader as bt

  File "C:\Users\Liu\Anaconda3\lib\site-packages\backtrader\__init__.py", line 62, in <module>
    from .cerebro import *

  File "C:\Users\Liu\Anaconda3\lib\site-packages\backtrader\cerebro.py", line 35, in <module>
    from .brokers import BackBroker

  File "C:\Users\Liu\Anaconda3\lib\site-packages\backtrader\brokers\__init__.py", line 40, in <module>
    from .oandabroker import OandaBroker

  File "C:\Users\Liu\Anaconda3\lib\site-packages\backtrader\brokers\oandabroker.py", line 36, in <module>
    from backtrader.stores import oandastore

  File "C:\Users\Liu\Anaconda3\lib\site-packages\backtrader\stores\oandastore.py", line 41, in <module>
    class OandaRequestError(oandapy.OandaError):

AttributeError: module 'oandapy' has no attribute 'OandaError'

**Comment by koverus** [comment]
I fixed this by ensuring the files were in the correct folders and making sure all imports were not failing.  
After, that I traced/tested (using IDE intellisense) what properties were being exposed from the module.
